### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Rych\Bencode\Bencode::decodeFile()

### ISSUE THREAD

**Issue by newadventure079** [OPSnet/bencode-torrent#5]
I run this code:
```
use OrpheusNET\BencodeTorrent;
$bencode = new Bencode();
$bencode->decodeFile('/path/to/file');
```

And I get this error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Rych\Bencode\Bencode::decodeFile() in /Users/user/Documents/code/projects/torrents_missing_on_sites/torrents_populate_cross_seed_dir.php:8
Stack trace:
#0 {main}
  thrown in /Users/user/Documents/code/projects/torrents_missing_on_sites/torrents_populate_cross_seed_dir.php on line 8

Fatal error: Uncaught Error: Call to undefined method Rych\Bencode\Bencode::decodeFile() in /Users/user/Documents/code/projects/torrents_missing_on_sites/torrents_populate_cross_seed_dir.php:8
Stack trace:
#0 {main}
  thrown in /Users/user/Documents/code/projects/torrents_missing_on_sites/torrents_populate_cross_seed_dir.php on line 8
```

**Comment by itismadness** [comment]
The usage example was not correct as it should have been `new BencodeTorrent()` and not `new Bencode()`. It seems that for you, the latter is targeting https://packagist.org/packages/rych/bencode, which is an unrelated library as well, vs the `OrpheusNET/Bencode` class that is shipped within this library.

I have updated the README in 922a60224d7acb06aa67370f9515e23e8e888df4 and fe026fb3a3ec0257aceefc18465e11c5821bd3a2 so that the usage example should now be correct to minimally get started with this library.
